### ISSUE TITLE
Could you please upload the simulation for Godot ?

### ISSUE THREAD

**Issue by www8098** [xc-jp/InsertionAI#4]
Dear Professor,

I am really impressed by your work on residual reinforcement learning and insertion AI.  I want to repeat your experiment but find the links for simulation for Godot and Unity failed.

Could you please re-upload the simulation?  Thank you for opening source such a good project.

Best regards,

**Comment by sachitotakahashi-vienna** [comment]
@www8098 

Hi, I asked internal people about this repo, the content is not very important for us and we are not currently maintaining it.
Sorry. I think I will make this repo private to avoid such misunderstanding.

**Comment by sachitotakahashi-vienna** [comment]
@www8098 The author of the code allowed his private repo for Godot to be public. Please try once again.
